# Generated by Django 5.1.4 on 2026-03-16 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('PRODUTOR', 'Produtor')], db_index=True, default='PRODUTOR', max_length=20, verbose_name='Perfil')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempt', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail utilizado')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Login bem-sucedido')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_audits', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Auditoria de Login',
                'verbose_name_plural': 'Auditorias de Login',
                'db_table': 'login_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', 'success', 'timestamp'], name='idx_audit_ip_success_ts'), models.Index(fields=['user', 'timestamp'], name='idx_audit_user_ts')],
            },
        ),
    ]
