# Generated by Django 5.1.4 on 2026-04-27 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_talhao_area_produtiva_talhao_codigo_talhao_cultura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da safra')),
                ('cultura', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('cafe', 'Café'), ('algodao', 'Algodão'), ('outro', 'Outro')], max_length=20, verbose_name='Cultura')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safras', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safras', to='properties.propriedade', verbose_name='Propriedade')),
                ('talhoes', models.ManyToManyField(blank=True, related_name='safras', to='properties.talhao', verbose_name='Talhões')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
                'ordering': ['-created_at'],
            },
        ),
    ]
