# Generated by Django 5.1.4 on 2026-05-17 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoSafra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da Simulação')),
                ('cultura', models.CharField(choices=[('soja', 'Soja'), ('milho', 'Milho'), ('cafe', 'Café'), ('algodao', 'Algodão'), ('outro', 'Outro')], max_length=20, verbose_name='Cultura')),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (ha)')),
                ('nivel_tecnologico', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=10, verbose_name='Nível Tecnológico')),
                ('preco_saca_esperado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Saca (R$)')),
                ('custo_sementes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_fertilizantes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo_defensivos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produtividade_esperada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Produtividade Esperada (sc/ha)')),
                ('custo_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Custo Total Estimado (R$)')),
                ('receita_projetada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Receita Projetada (R$)')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margem de Lucro (%)')),
                ('ponto_equilibrio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ponto de Equilíbrio (sc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Simulação de Safra',
                'verbose_name_plural': 'Simulações de Safra',
                'ordering': ['-created_at'],
            },
        ),
    ]
