# Generated by manual refactoring on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models

def migrate_data(apps, schema_editor):
    SimulacaoSafra = apps.get_model('planting', 'SimulacaoSafra')
    for simulacao in SimulacaoSafra.objects.all():
        if simulacao.area_hectares > 0:
            simulacao.custo_por_hectare = simulacao.custo_total_estimado / simulacao.area_hectares
        else:
            simulacao.custo_por_hectare = 0
        simulacao.save()

class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0002_simulacaosafra'),
    ]

    operations = [
        # Step 1: Add new field allowing nulls temporarily
        migrations.AddField(
            model_name='simulacaosafra',
            name='custo_por_hectare',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                blank=True,
                verbose_name='Custo por Hectare (R$/ha)'
            ),
        ),
        # Step 2: Run Python script to backfill data from older records
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        # Step 3: Make custo_por_hectare NOT NULL
        migrations.AlterField(
            model_name='simulacaosafra',
            name='custo_por_hectare',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                default=0,
                verbose_name='Custo por Hectare (R$/ha)'
            ),
        ),
        # Step 4: Drop old level technology column and estimates
        migrations.RemoveField(
            model_name='simulacaosafra',
            name='nivel_tecnologico',
        ),
        migrations.RemoveField(
            model_name='simulacaosafra',
            name='custo_sementes',
        ),
        migrations.RemoveField(
            model_name='simulacaosafra',
            name='custo_fertilizantes',
        ),
        migrations.RemoveField(
            model_name='simulacaosafra',
            name='custo_defensivos',
        ),
    ]
