# Generated by Django 5.1.4 on 2026-04-27 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_talhao_area_produtiva_talhao_codigo_talhao_cultura_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do insumo')),
                ('tipo', models.CharField(choices=[('semente', 'Semente'), ('fertilizante', 'Fertilizante'), ('defensivo', 'Defensivo'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('unidade_medida', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (L)'), ('ml', 'Mililitro (mL)'), ('sc', 'Saca (sc)'), ('t', 'Tonelada (t)'), ('un', 'Unidade (un)')], max_length=5, verbose_name='Unidade de medida')),
                ('fornecedor', models.CharField(blank=True, default='', max_length=200, verbose_name='Fornecedor')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário (R$)')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque mínimo')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='properties.propriedade', verbose_name='Propriedade')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da entrada')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário (R$)')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo total (R$)')),
                ('numero_nota_fiscal', models.CharField(blank=True, default='', max_length=100, verbose_name='Nº da nota fiscal')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='estoque.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Entrada de Estoque',
                'verbose_name_plural': 'Entradas de Estoque',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da saída')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário no momento (R$)')),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo total (R$)')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('lancado_financeiro', models.BooleanField(default=False, verbose_name='Lançado no financeiro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_estoque', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='estoque.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Saída de Estoque',
                'verbose_name_plural': 'Saídas de Estoque',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
