# Generated by Django 5.1.4 on 2026-04-27 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('planting', '0001_initial'),
        ('properties', '0002_talhao_area_produtiva_talhao_codigo_talhao_cultura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='safra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_estoque', to='planting.safra', verbose_name='Safra'),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='talhao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_estoque', to='properties.talhao', verbose_name='Talhão'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('propriedade', 'nome'), name='unique_insumo_ativo_por_propriedade'),
        ),
    ]
