# Generated by Django 5.1.4 on 2026-05-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_talhao_area_produtiva_talhao_codigo_talhao_cultura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da cultura')),
                ('temp_min_ideal', models.FloatField(verbose_name='Temperatura Mínima Ideal')),
                ('temp_max_ideal', models.FloatField(verbose_name='Temperatura Máxima Ideal')),
                ('chuva_max_diaria', models.FloatField(verbose_name='Chuva Máxima Diária (mm)')),
                ('temp_critica_geada', models.FloatField(default=4.0, verbose_name='Temperatura Crítica de Geada')),
            ],
            options={
                'verbose_name': 'Cultura',
                'verbose_name_plural': 'Culturas',
            },
        ),
        migrations.AlterField(
            model_name='talhao',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.cultura', verbose_name='Cultura principal'),
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da consulta')),
                ('classification_summary', models.JSONField(verbose_name='Resumo da classificação (10 dias)')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_clima', to='properties.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Histórico Meteorológico',
                'verbose_name_plural': 'Históricos Meteorológicos',
                'ordering': ['-consulted_at'],
            },
        ),
    ]
