# Generated by Django 5.1.4 on 2026-05-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_cultura_alter_talhao_cultura_weatherhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherHistory',
        ),
    ]
