# Generated by Django 5.1.4 on 2026-05-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0004_delete_weatherhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da consulta')),
                ('classification_summary', models.JSONField(verbose_name='Resumo da classificação (10 dias)')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_clima_app', to='properties.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Histórico Meteorológico',
                'verbose_name_plural': 'Históricos Meteorológicos',
                'ordering': ['-consulted_at'],
            },
        ),
    ]
